# An example of a Kopie configuration file

# Just for logging purposes, incase you are running multiple different
# configuration files
label = "Kopie default configuration."
#suffix is used when kopie has generated tables
suffix = "_kopie"

[[databases]]
  name = "kopie_test"
  type = "postgres"
  host = "localhost"
  port = 5432
  user = "kopie"
  password = "kopietestpw"
  sslmode = "disable"
  [[databases.tables]]
    name = "test"
    replicate = true
  [[databases.tables]]
    name = "test2"
    replicate = true

[[databases]]
  name = "kopie_test2"
  type = "postgres"
  host = "localhost"
  port = 5432
  user = "kopie"
  password = "kopietestpw"
  sslmode = "disable"
  [[databases.tables]]
    name = "test"
    replicate = true
  [[databases.tables]]
    name = "test2"
    replicate = true

[[protocols]]
  name = "mainProcedure"
  type = "pump"
  [protocols.pump]
   master = "kopie_test"
   tables = [
        "test",
        "test2",
   ]
   slave = "kopie_test2"
   automigrate = true
   period = 1

[[protocols]]
  name = "testProcedure"
  type = "testprotocol"
  [protocols.test]
   file = "testprotocol.test"
   message = "Testing"



    
